steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config','set','project','$_PROJECT_ID']

  #deploy Deploy Workflow - EDA
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud workflows deploy aible-eda --source=eda.yml --location=${_LOCATION} --service-account=${_SA_EMAIL}
  #deploy to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'

    - 'deploy'

    - '${_EXEC_SERVICE_NAME}'

    - '--image'
    - '${_LOCATION}-docker.pkg.dev/$_PROJECT_ID/${_REPOSITORY}/${_EXEC_SERVICE_NAME}:${_VERSION}'

    - '--region'
    - '${_LOCATION}'

    - '--platform'
    - 'managed'
    
    - '--service-account'
    - '${_SA_EMAIL}'

    - '--update-secrets'
    - 'AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest, S3Source=S3Source:latest, AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _PROJECT_ID: 'aible-gcp-containers-beta'
    _LOCATION: 'us-central1'
    _EXEC_SERVICE_NAME: 'aible-exec'
    _REPOSITORY: 'gcp'
    _VERSION: '216e458'
    _PORT: '8000'
    _SA_EMAIL: 'aible-app-sa@aible-gcp-containers-beta.iam.gserviceaccount.com'